### ISSUE TITLE
cannot update the world file 

### ISSUE THREAD

**Issue by jmarrr** [yukkysaito/vehicle_model#5]
Building osrf_citysim with Gazebo 9 `erb simple_city.world.erb > simple_city.world` throws me this error:

```
/usr/bin/erb:125:in `set_encoding': No such file or directory @ rb_sysopen - simple_city.world.erb (Errno::ENOENT)
	from /usr/bin/erb:125:in `run'
	from /usr/bin/erb:170:in `<main>'
```
I'm using ROS kinetic and Ubuntu 16.04

**Comment by yukkysaito** [comment]
As you said, I also got this error.
However, as we do not need to update the world, that work is not necessary
https://bitbucket.org/osrf/citysim

So, you can run the citysim with gazebo9.
```
$ roslaunch vehicle_sim gazebo9_citysim_autoware.launch gpu:=true
```
